
---
- hosts: web-server
  become: yes

  tasks:
    - name: install deps
      apt: name={{item}} state=present
      with_items:
      - gcc
      - php-pear
      tags: php-mongo

    - name: set pecl php.ini location
      shell: pecl config-set php_ini /etc/php5/apache2/php.ini
      tags: php-mongo

    - name: determine php extensions directory
      shell: php -i | grep -i '^extension_dir' | awk '{print $3}'
      register: php_extension_dir
      tags: php-mongo

    - name: install MongoClient for php
      shell: printf "\n" | pecl install mongo creates={{php_extension_dir.stdout_lines[0]}}/mongo.so
      tags: php-mongo

    - name: make mongo.so executable
      file: path={{php_extension_dir.stdout_lines[0]}}/mongo.so mode=0755
      tags: php-mongo

    - name: add json extension to php.ini configuration
      lineinfile: dest=/etc/php5/apache2/php.ini
                  line="extension=json.so"
                  state=present
      tags: php-mongo

    - name: add mongo extension to php.ini configuration
      lineinfile: dest=/etc/php5/apache2/php.ini
                  line="extension=mongo.so"
                  state=present
      tags: php-mongo

    - name: Restart Apache
      action: service name=apache2 state=restarted
      tags: php-mongo
