---
- hosts: db-server
  become: yes

  vars_files:
    # Contains configuration to deploy on the machine such as Apache vhost, mysql databases...
    - vars/configuration.yml

  pre_tasks:
    - name: Create dynamic MySQL variables.
      set_fact:
        mysql_users:
          - name: mycompany_user
            host: "{{ groups['web-server'][0] }}"
            password: secret
            priv: "*.*:SELECT"
          # - name: mycompany_user
          #   host: "{{ groups['web-server'][1] }}"
          #   password: secret
          #   priv: "*.*:SELECT"
        #mysql_replication_master: "{{ groups['db-server'][0] }}"

  roles:
    - geerlingguy.mysql
