---

- hosts: web-server
  become: yes

  vars_files:
    # Contains variables an settings required for installing the environement
    - vars/settings.yml
    # Contains configuration to deploy on the machine such as Apache vhost, mysql databases...
    - vars/configuration.yml

  tasks:
  ##
   # FTP server setup.
   #
     - name: FTP | vsftpd daemon package
       action: apt pkg=vsftpd state=installed
       tags: ftp

     - name: FTP | Configuration setup
       action: template src=templates/etc-vsftpd-conf.j2 dest=/etc/vsftpd.conf
       tags: ftp

     - name: Create FTP user group
       action: group name=ftp-users state=present system=yes
       tags: ftp

     - name: Chmod /var/www folder
       action: file path=/var/www state=directory owner=root group=ftp-users mode=0775 recurse=yes
       tags: ftp

     - name: Create user
       action: user name={{ item.ftp_user }} password={{ item.ftp_password }} update_password=always group=ftp-users home=/var/www shell=/bin/bash
       with_items: vsftpd_user
       when: vsftpd_user
       tags: ftp

     ##
     # TODO  chown ftp-u:ftp-users /var/www
     #
     - name: Change directory permission
       action: file path={{ item }} state=directory group=ftp-users owner=ftp-u1 mode=0775 recurse=yes
       with_items:
         - /var/www/
       tags: chmod

     - name: Restart vsftpd
       action: service name=vsftpd state=restarted
       tags: ftp
